name: Build CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Enable source-code
      run: |
        sudo sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        sudo apt update
    
    - name: Install dependencies
      run: sudo apt build-dep gnome-control-center

    - name: Build and Install
      run: |
        meson build
        cd build
        sudo ninja install
